---
- hosts: all
#  serial: 1
  gather_facts: true
  become: yes
  
  
  tasks:
  
#RHEL CENTOS RPM etc..
  - name: Yum - list security updates
    yum:
        list: security
    register: rhel_result
    when: ansible_pkg_mgr  == "yum" or ansible_pkg_mgr == "dnf"


  - debug:
      var: rhel_result
     # verbosity: 1
    when: ansible_pkg_mgr  == "yum" or ansible_pkg_mgr == "dnf"


  - name: Yum - install security updates
    yum:
        name: '*'
        security: yes
        state: latest
    become: true
    become_user: root
    become_method: sudo
    when: ansible_pkg_mgr  == "yum" or ansible_pkg_mgr == "dnf"

#UBUNTU DEB etc..
  - name: DEB - Make a copy of security repos
    shell: cat /etc/apt/sources.list|grep secu >/etc/apt/security.sources.list
    become: true
    become_user: root
    become_method: sudo
    when: ansible_pkg_mgr  == "apt"
    
    
  - name: DEB - update apt list
    apt:
      update_cache: yes
    become: true
    become_user: root
    become_method: sudo
    when: ansible_pkg_mgr  == "apt"

  - name: DEB - Install security updates
    shell: apt-get upgrade -oDir::Etc::SourceList=/etc/apt/security.sources.list --force-yes -y
    become: true
    become_user: root
    become_method: sudo
    register: deb_result
    when: ansible_pkg_mgr  == "apt"
    
  - debug:
      var: deb_result
     # verbosity: 1
    when: ansible_pkg_mgr  == "apt"
